// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RoomBooking.Api.Data;

#nullable disable

namespace RoomBooking.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260215153518_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("RoomBooking.Api.Models.RoomBookingEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Keperluan")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Peminjam")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("RoomId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("TanggalMulai")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("TanggalSelesai")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("RoomBookings");
                });
#pragma warning restore 612, 618
        }
    }
}
